/// Map of emojis, with the name as key
Map<String, String> emojiData = {
  "4chan Emoticon": "( ͡° ͜ʖ ͡°)",
  "GTFO Bear": "ʕ •`ᴥ•´ʔ",
  "Angry Birds": "( ఠൠఠ )ﾉ",
  "Angry Face": "(╬ ಠ益ಠ)",
  "Angry Troll": "ヽ༼ ಠ益ಠ ༽ﾉ",
  "At What Cost": "ლ(ಠ益ಠლ)",
  "Barf": "(´ж｀ς)",
  "Basking In Glory": "ヽ(´ー｀)ノ",
  "Boxing": "ლ(•́•́ლ)",
  "Breakdown": "ಥ﹏ಥ",
  "Careless": "◔_◔",
  "Cheers": "（ ^_^）o自自o（^_^ ）",
  "Chicken": "ʚ(•｀",
  "Confused": "¿ⓧ_ⓧ?",
  "Confused Scratch": "(⊙.☉)7",
  "Crazy": "ミ●﹏☉ミ",
  "Creeper": "ƪ(ړײ)‎ƪ​​",
  "Cry Face": "｡ﾟ( ﾟஇ‸இﾟ)ﾟ｡",
  "Cry Troll": "༼ ༎ຶ ෴ ༎ຶ༽",
  "Crying Face": "ಥ_ಥ",
  "Cute Bear": "ʕ•ᴥ•ʔ",
  "Cute Face With Big Eyes": "(｡◕‿◕｡)",
  "Dab": "ヽ( •_)ᕗ",
  "Dance": "♪♪ ヽ(ˇ∀ˇ )ゞ",
  "Dancing": "┌(ㆆ㉨ㆆ)ʃ",
  "Dear God Why": "щ（ﾟДﾟщ）",
  "Devious Smile": "ಠ‿ಠ",
  "Disagree": "٩◔̯◔۶",
  "Discombobulated": "⊙﹏⊙",
  "Dislike": "( ಠ ʖ̯ ಠ)",
  "Do You Even Lift Bro": " ᕦ(ò_óˇ)ᕤ",
  "Double Flip": "┻━┻ ︵ヽ(`Д´)ﾉ︵﻿ ┻━┻",
  "Emo Dance": "ヾ(-_- )ゞ",
  "Excited": "☜(⌒▽⌒)☞",
  "Exorcism": "ح(•̀ж•́)ง †",
  "Eye Roll": "⥀.⥀",
  "Feel Perky": "(`･ω･´)",
  "Fido": "V•ᴥ•V",
  "Fight": "(ง'̀-'́)ง",
  "Fisticuffs": "ლ(｀ー´ლ)",
  "Flexing": "ᕙ(⇀‸↼‶)ᕗ",
  "Flip Friend": "(ノಠ ∩ಠ)ノ彡( \\o°o)\\",
  "Fly Away": "⁽⁽ଘ( ˊᵕˋ )ଓ⁾⁾",
  "Flying": "ح˚௰˚づ",
  "Fuck It": "t(-_-t)",
  "Fuck Off": "(° ͜ʖ͡°)╭∩╮",
  "Happy Face": "ヽ(´▽`)/",
  "Happy Hug": "\\(ᵔᵕᵔ)/",
  "Hitchhiking": "(งツ)ว",
  "Hugger": "(づ￣ ³￣)づ",
  "Im A Hugger": "(⊃｡•́‿•̀｡)⊃",
  "Injured": "(҂◡_◡)",
  "Innocent Face": "ʘ‿ʘ",
  "Japanese Lion Face": "°‿‿°",
  "Judgemental": "{ಠʖಠ}",
  "Judging": "( ఠ ͟ʖ ఠ)",
  "Kirby": "⊂(◉‿◉)つ",
  "Kissing": "( ˘ ³˘)♥",
  "Kitty Emote": "ᵒᴥᵒ#",
  "Listening To Headphones": "◖ᵔᴥᵔ◗ ♪ ♫",
  "Looking Down": "(._.)",
  "Love": "-`ღ´-",
  "Meh": "¯\\(°_o)/¯",
  "Meow": "ฅ^•ﻌ•^ฅ",
  "No Support": "乁( ◔ ౪◔)「      ┑(￣Д ￣)┍",
  "Opera": "ヾ(´〇`)ﾉ♪♪♪",
  "Peepers": "ಠಠ",
  "Pointing": "(☞ﾟヮﾟ)☞",
  "Pretty Eyes": "ఠ_ఠ",
  "Put The Table Back": "┬─┬﻿ ノ( ゜-゜ノ)",
  "Questionable": "(Ծ‸ Ծ)",
  "Reddit Disapproval Face": "ಠ_ಠ",
  "Resting My Eyes": "ᴖ̮ ̮ᴖ",
  "Robot": "{•̃_•̃}",
  "Running": "ε=ε=ε=┌(;*´Д`)ﾉ",
  "Sad And Confused": "¯\\_(⊙︿⊙)_/¯",
  "Sad And Crying": "(ᵟຶ︵ ᵟຶ)",
  "Sad Face": "(ಥ⌣ಥ)",
  "Satisfied": "(◠﹏◠)",
  "Seal": "(ᵔᴥᵔ)",
  "Shark Face": "( ˇ෴ˇ )",
  "Shrug Face": "¯\\_(ツ)_/¯",
  "Shy": "(๑•́ ₃ •̀๑)",
  "Sleepy": "눈_눈",
  "Smiley Toast": "ʕʘ̅͜ʘ̅ʔ",
  "Squinting Bear": "ʕᵔᴥᵔʔ",
  "Staring": "٩(๏_๏)۶",
  "Stranger Danger": "(づ｡◕‿‿◕｡)づ",
  "Strut": "ᕕ( ᐛ )ᕗ",
  "Stunna Shades": "(っ▀¯▀)つ",
  "Surprised": "（　ﾟДﾟ）",
  "Table Flip": "(╯°□°）╯︵ ┻━┻",
  "Taking A Dump": "(⩾﹏⩽)",
  "Tgif": "“ヽ(´▽｀)ノ”",
  "Things That Cant Be Unseen": "♨_♨",
  "Tidy Up": "┬─┬⃰͡ (ᵔᵕᵔ͜ )",
  "Tired": "( ͡ಠ ʖ̯ ͡ಠ)",
  "Touchy Feely": "ԅ(≖‿≖ԅ)",
  "Tripping Out": "q(❂‿❂)p",
  "Trolling": "༼∵༽ ༼⍨༽ ༼⍢༽ ༼⍤༽",
  "Wave Dance": "~(^-^)~",
  "Whistling": "(っ•́｡•́)♪♬",
  "Winnie The Pooh": "ʕ •́؈•̀)",
  "Winning": "(•̀ᴗ•́)و ̑̑",
  "Wizard": "(∩｀-´)⊃━☆ﾟ.*･｡ﾟ",
  "Worried": "(´･_･`)",
  "Yum": "(っ˘ڡ˘ς)",
  "Zombie": "[¬º-°]¬",
  "Zoned": "(⊙_◎)"
};
